name: jeesite_des
description: Jeesite 4's des algorithm.
version: 0.0.1
homepage: https://github.com/shengdoushi/jeesite-des-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
